### ISSUE TITLE
Could I do room setup without headset?

### ISSUE THREAD

**Issue by lqh929289158** [ashtuchkin/vive-diy-position-sensor-geometry-getter#1]
Hi, I really appreciate you work.

I have almost understood your project vive-day-position-sensor, but now I have some problems about getting the base station geometry.

Since I have no headset, is it possible to complete the room setup just with controller and steamVR?

If No, is there any idea that I could compute the base station geometry by myself with multiple sensors like the HTC Vive controller?

I am looking forward to you reply. :)

**Comment by jayaramanrp** [comment]
do you know where to add the calculated base station geometry , which we get from that application?

**Comment by ashtuchkin** [comment]
No; you'll likely have to precisely calculate positions and angles of the base stations and then apply some 3d vector/matrix magic. I haven't done these calculations myself, so can't help with it, sorry.
